Re-run the check after cleaning up

diff --git a/.github/actions/setup-miniconda/action.yml b/.github/actions/setup-miniconda/action.yml
--- a/.github/actions/setup-miniconda/action.yml
+++ b/.github/actions/setup-miniconda/action.yml
@@ -154,34 +154,51 @@ runs:
           echo "Print the available disk space for manual inspection"
           df -h
 
-          # Set the minimum requirement space to 4GB
-          MINIMUM_AVAILABLE_SPACE_IN_GB=4
-          MINIMUM_AVAILABLE_SPACE_IN_KB=$(($MINIMUM_AVAILABLE_SPACE_IN_GB * 1024 * 1024))
+          function check_disk_space() {
+            set +e
 
-          # Use KB to avoid floating point warning like 3.1GB
-          df -k | tr -s ' ' | cut -d' ' -f 4,9 | while read -r LINE;
-          do
-            AVAIL=$(echo $LINE | cut -f1 -d' ')
-            MOUNT=$(echo $LINE | cut -f2 -d' ')
+            # Set the minimum requirement space to 4GB
+            MINIMUM_AVAILABLE_SPACE_IN_GB=4
+            MINIMUM_AVAILABLE_SPACE_IN_KB=$(($MINIMUM_AVAILABLE_SPACE_IN_GB * 1024 * 1024))
 
-            if [ "${MOUNT}" = "/" ]; then
-              if [ "${AVAIL}" -lt "${MINIMUM_AVAILABLE_SPACE_IN_KB}" ]; then
-                echo "There is only ${AVAIL}KB free space left in ${MOUNT}, which is less than the minimum requirement of ${MINIMUM_AVAILABLE_SPACE_IN_KB}KB for ${RUNNER_OS}"
+            # Use KB to avoid floating point warning like 3.1GB
+            df -k | tr -s ' ' | cut -d' ' -f 4,9 | while read -r LINE;
+            do
+              AVAIL=$(echo $LINE | cut -f1 -d' ')
+              MOUNT=$(echo $LINE | cut -f2 -d' ')
 
-                if [ "${RUNNER_OS}" = "macOS" ]; then
-                  # We can clean up /System/Library/Caches/com.apple.coresymbolicationd on MacOS to free up the space and this should free up enough space
-                  # https://github.com/pytorch/pytorch/issues/85440
-                  sudo rm "/System/Library/Caches/com.apple.coresymbolicationd/data" || true
-                  # Stop the daemon and launchctl will automatically start it again, thus accomplish a restart and free up the above file
-                  sudo launchctl stop com.apple.coresymbolicationd
-
-                  df -h
+              if [ "${MOUNT}" = "/" ]; then
+                if [ "${AVAIL}" -lt "${MINIMUM_AVAILABLE_SPACE_IN_KB}" ]; then
+                  echo "Failure: There is only ${AVAIL}KB free space left in ${MOUNT}, which is less than the minimum requirement of ${MINIMUM_AVAILABLE_SPACE_IN_KB}KB for ${RUNNER_OS}"
                 else
-                  echo "Please help create an issue to PyTorch Release Engineering via https://github.com/pytorch/test-infra/issues and provide the link to the workflow run."
-                  exit 1;
+                  echo "Success: There is ${AVAIL}KB free space left in ${MOUNT} for ${RUNNER_OS}, continue"
                 fi
-              else
-                echo "There is ${AVAIL}KB free space left in ${MOUNT} for ${RUNNER_OS}, continue"
               fi
-            fi
-          done
+            done
+
+            set -e
+          }
+
+          RESULT=$(check_disk_space)
+          echo "${RESULT}"
+
+          if [[ "${RESULT}" == *Failure* && "${RUNNER_OS}" == "macOS" ]]; then
+            # We can clean up /System/Library/Caches/com.apple.coresymbolicationd on MacOS to free up the space and this should free up enough space
+            # https://github.com/pytorch/pytorch/issues/85440
+            sudo rm "/System/Library/Caches/com.apple.coresymbolicationd/data" || true
+            # Stop the daemon and launchctl will automatically start it again, thus accomplish a restart and free up the above file
+            sudo launchctl stop com.apple.coresymbolicationd || true
+
+            echo "Re-run disk space check for ${RUNNER_OS} after cleaning up"
+            # Re-run the check
+            RESULT=$(check_disk_space)
+            echo "${RESULT}"
+          fi
+
+          if [[ "${RESULT}" == *Failure* ]]; then
+            echo "Please help create an issue to PyTorch Release Engineering via https://github.com/pytorch/test-infra/issues and provide the link to the workflow run."
+            exit 1
+          fi
+
+          echo "Print the available disk space for manual inspection after cleaning up"
+          df -h
