Upgrade MacOS conda to 23.1.0 and ensure that this version is used by the CI (#4028)
After some debugging, I think I have found the potential root cause of
the flaky missing dependencies on MacOS. It is in the conda clone step
in which only conda packages are copied over but not pip (untracked)
files.

For example, in this failure example
https://github.com/pytorch/pytorch/actions/runs/4692698401/jobs/8318918238
had:

```
Source:      /Users/ec2-user/runner/_work/_temp/conda-python-3.9.12
Destination: /Users/ec2-user/runner/_work/_temp/conda_environment_4692698401
Packages: 58
Files: 0 <--- Nothing here
```

And it used `/Users/ec2-user/runner/_work/_temp/miniconda/bin/conda` as
reported by `which conda`. This conda is correct but old 4.12.0
(https://github.com/pytorch/test-infra/blob/main/.github/actions/setup-miniconda/action.yml#L15).

On the other hand, when working correctly, these files should have been
copied over to the cloned env:

```
Source:      /Users/ec2-user/runner/_work/_temp/conda-python-3.9.12
Destination: /Users/ec2-user/runner/_work/_temp/conda_environment_4683905314
Packages: 58
Files: 13010 <-- These files are copied over
```

This conda here was `/opt/homebrew/Caskroom/miniconda/base/bin/conda` on
M1 and `/usr/local/bin/conda` on x86_64.
Both are newer (23.1.0). It seems that **we unknowingly use the newer
system-wide conda on MacOS**, which is not part of the CI.

So the attempt fix here is to:

* Upgrade MacOS conda to
[23.1.0](https://repo.anaconda.com/miniconda/Miniconda3-py39_23.1.0-1-MacOSX-arm64.sh).
My theory is that the conda clone issue was fixed by this
https://github.com/conda/conda/pull/11364
* Always use `/Users/ec2-user/runner/_work/_temp/miniconda/bin/conda` as
this is supposed to be the one controlled by the CI
* Check if the number of untracked files (pip dependencies) is 0. If it
is, reinstall pip requirements directly on the cloned conda environment

### Testing


https://github.com/pytorch/pytorch/actions/runs/4695636286/jobs/8338451917

* Use `/Users/ec2-user/runner/_work/_temp/miniconda/bin/conda`
* Use `conda 23.1.0`
* Files are copied correctly

diff --git a/.github/actions/setup-miniconda/action.yml b/.github/actions/setup-miniconda/action.yml
--- a/.github/actions/setup-miniconda/action.yml
+++ b/.github/actions/setup-miniconda/action.yml
@@ -12,7 +12,7 @@ inputs:
     description: Miniconda version to install
     required: false
     type: string
-    default: "4.12.0"
+    default: "23.1.0-1"
   environment-file:
     description: Environment file to install dependencies from
     required: false
@@ -73,8 +73,13 @@ runs:
       - name: Update GitHub path to include miniconda install
         shell: bash
         run: |
+          set -x
+
           MINICONDA_INSTALL_PATH="${RUNNER_TEMP}/miniconda"
           echo "${MINICONDA_INSTALL_PATH}/bin" >> $GITHUB_PATH
+          # NB: GITHUB_PATH has a lower priority than PATH, so also set the path
+          # here to make sure that the correct conda is used
+          echo "PATH=${MINICONDA_INSTALL_PATH}/bin:${PATH}" >> $GITHUB_ENV
 
       # When the environment-file or pip-requirements-file inputs are not set or are set to invalid paths, the hashFiles
       # function will return an empty string without failing the step. This works out nicely and we can have a various
@@ -115,6 +120,10 @@ runs:
             CONDA_EXTRA_FLAGS=" -c pytorch-nightly"
           fi
 
+          # Print the conda we are using here in case we need debugging information
+          which conda
+          conda --version
+
           conda create \
             --yes --quiet \
             --prefix "${CONDA_BASE_ENV}" \
@@ -137,12 +146,34 @@ runs:
         env:
           PYTHON_VERSION: ${{ inputs.python-version }}
           CONDA_BASE_ENV: ${{ runner.temp }}/conda-python-${{ inputs.python-version }}
+          PIP_REQUIREMENTS_FILE: ${{ inputs.pip-requirements-file }}
         run: |
+          set -x
+
+          # Print the conda we are using here in case we need debugging information
+          which conda
+          conda --version
+
           CONDA_ENV="${RUNNER_TEMP}/conda_environment_${GITHUB_RUN_ID}"
           conda create \
             --yes --quiet \
             --prefix "${CONDA_ENV}" \
             --clone "${CONDA_BASE_ENV}"
+
+          set +e
+          # NB: Cloning sometimes doesn't copied pip dependencies (untracked files) over. If this
+          # happens, let's attempt to install the pip requirements directly on top of the cloned
+          # environment. This is to make sure that no dependency is missing.
+          UNTRACKED_FILES_COUNT=$(conda package -p "${CONDA_ENV}" -u | grep -v "^#" | wc -l | xargs)
+          set -e
+
+          if [[ -z "${UNTRACKED_FILES_COUNT}" ]] || [[ "${UNTRACKED_FILES_COUNT}" == "0" ]]; then
+            if [[ -f "${PIP_REQUIREMENTS_FILE}" ]]; then
+              conda run -p "${CONDA_ENV}" --no-capture-output python3 -mpip install -r "${PIP_REQUIREMENTS_FILE}"
+            elif [[ -n "${PIP_REQUIREMENTS_FILE}" ]]; then
+              echo "::warning::Specified pip requirements file (${PIP_REQUIREMENTS_FILE}) not found, not going to include it"
+            fi
+          fi
 
           echo "CONDA_ENV=${CONDA_ENV}" >> "${GITHUB_ENV}"
           echo "CONDA_RUN=conda run -p ${CONDA_ENV} --no-capture-output" >> "${GITHUB_ENV}"
@@ -152,6 +183,7 @@ runs:
           else
             echo "CONDA_INSTALL=conda install --yes --quiet -p ${CONDA_ENV}" >> "${GITHUB_ENV}"
           fi
+
       - name: Reset channel priority
         shell: bash -l {0}
         run: |
