tc

diff --git a/.github/actions/update-viablestrict/action.yml b/.github/actions/update-viablestrict/action.yml
--- a/.github/actions/update-viablestrict/action.yml
+++ b/.github/actions/update-viablestrict/action.yml
@@ -55,13 +55,6 @@ runs:
       with:
         python-version: '3.11'
 
-    # - name: Checkout test-infra for the fetch_latest_green_commit scripts
-    #   uses: actions/checkout@v3
-    #   with:
-    #     repository: ${{ inputs.test-infra-repository }}
-    #     ref: ${{ inputs.test-infra-ref }}
-    #     path: test-infra
-
     - uses: actions/checkout@v3
       with:
         repository: ${{ inputs.repository }}
@@ -85,34 +78,36 @@ runs:
       run: |
         set -ex
 
-        export PYTHONPATH=${PYTHONPATH}:${GITHUB_ACTION_PATH}/../../..
-        output=$(python ${GITHUB_ACTION_PATH}/../../../tools/scripts/fetch_latest_green_commit.py \
+        TEST_INFRA_PATH="${GITHUB_ACTION_PATH}/../../.."
+
+        export PYTHONPATH=${PYTHONPATH}:${TEST_INFRA_PATH}
+        output=$(python ${TEST_INFRA_PATH}/tools/scripts/fetch_latest_green_commit.py \
           --required-checks "${{ inputs.requires }}" \
           --viable-strict-branch "viable/strict" \
           --main-branch "master")
         echo "latest_viable_sha=$output" >> "${GITHUB_OUTPUT}"
 
-    # - name: Push SHA to viable/strict branch
-    #   if: steps.get-latest-commit.outputs.latest_viable_sha != 'None'
-    #   working-directory: ${{ inputs.repository }}
-    #   id: push-to-stable
-    #   env:
-    #     GITHUB_TOKEN: ${{ inputs.secret-bot-token }}
-    #     STABLE_BRANCH: ${{ inputs.stable-branch }}
-    #     LATEST_VIABLE_SHA: ${{ steps.get-latest-commit.outputs.latest_viable_sha }}
-    #   shell: bash
-    #   run: |
-    #     git config --global user.email "pytorchmergebot@users.noreply.github.com"
-    #     git config --global user.name "PyTorch MergeBot"
+    - name: Push SHA to viable/strict branch
+      if: steps.get-latest-commit.outputs.latest_viable_sha != 'None'
+      working-directory: ${{ inputs.repository }}
+      id: push-to-stable
+      env:
+        GITHUB_TOKEN: ${{ inputs.secret-bot-token }}
+        STABLE_BRANCH: ${{ inputs.stable-branch }}
+        LATEST_VIABLE_SHA: ${{ steps.get-latest-commit.outputs.latest_viable_sha }}
+      shell: bash
+      run: |
+        git config --global user.email "pytorchmergebot@users.noreply.github.com"
+        git config --global user.name "PyTorch MergeBot"
 
-    #     echo "Set the latest sha variable to be ${LATEST_VIABLE_SHA}"
-    #     # Pushing an older green commit here will fail because it's non-fast-forward, which is ok
-    #     # to ignore because we already have the later green commit in visable/strict
-    #     push_result=$(git push origin "${LATEST_VIABLE_SHA}:${STABLE_BRANCH}" 2>&1 || true)
-    #     {
-    #       echo 'push_result<<EOF'
-    #       echo $push_result
-    #       echo EOF
-    #     } >> "${GITHUB_OUTPUT}"
-    #     echo "${push_result}"
-    #     echo "time=$(date +%s)" >> "${GITHUB_OUTPUT}"
+        echo "Set the latest sha variable to be ${LATEST_VIABLE_SHA}"
+        # Pushing an older green commit here will fail because it's non-fast-forward, which is ok
+        # to ignore because we already have the later green commit in visable/strict
+        push_result=$(git push origin "${LATEST_VIABLE_SHA}:${STABLE_BRANCH}" 2>&1 || true)
+        {
+          echo 'push_result<<EOF'
+          echo $push_result
+          echo EOF
+        } >> "${GITHUB_OUTPUT}"
+        echo "${push_result}"
+        echo "time=$(date +%s)" >> "${GITHUB_OUTPUT}"
