Another tweak for always-rebuild

diff --git a/.github/actions/calculate-docker-image/action.yml b/.github/actions/calculate-docker-image/action.yml
--- a/.github/actions/calculate-docker-image/action.yml
+++ b/.github/actions/calculate-docker-image/action.yml
@@ -106,7 +106,7 @@ runs:
 
     - name: Check if image exists and build it if it doesnt
       id: check-and-build-image
-      if: ${{ steps.calculate-image.outputs.skip != 'true' && inputs.always-rebuild }}
+      if: ${{ steps.calculate-image.outputs.skip != 'true' }}
       env:
         REPO_NAME: ${{ github.event.repository.name }}
         BASE_REVISION: ${{ github.event.pull_request.base.sha || github.sha }}
@@ -115,6 +115,7 @@ runs:
         DOCKER_IMAGE: ${{ steps.calculate-image.outputs.docker-image }}
         DOCKER_TAG: ${{ steps.calculate-image.outputs.docker-tag }}
         DOCKER_REGISTRY: ${{ inputs.docker-registry }}
+        ALWAYS_REBUILD: ${{ inputs.always-rebuild }}
       # NB: Retry here as this step frequently fails with network error downloading various stuffs
       uses: nick-fields/retry@v3.0.0
       with:
@@ -143,42 +144,50 @@ runs:
             exit 0
           }
 
-          pushd "${WORKING_DIRECTORY}"
+          check_if_image_exists_and_build_it_if_not() {
+            pushd "${WORKING_DIRECTORY}"
 
-          # Check if image already exists, if it does then skip building it
-          if docker manifest inspect "${DOCKER_IMAGE}"; then
-            exit 0
-          fi
+            # Check if image already exists, if it does then skip building it
+            if docker manifest inspect "${DOCKER_IMAGE}"; then
+              exit 0
+            fi
 
-          # NB: This part requires a full checkout. Otherwise, the merge base will
-          # be empty.  The default action would be to continue rebuild the image
-          if [[ "$BASE_REVISION" = "$(git rev-parse HEAD)" ]]; then
-            # if we're on the base branch then use the parent commit
-            MERGE_BASE=$(git rev-parse HEAD~)
-          else
-            # otherwise we're on a PR, so use the most recent base commit
-            MERGE_BASE=$(git merge-base HEAD "$BASE_REVISION")
-          fi
+            # NB: This part requires a full checkout. Otherwise, the merge base will
+            # be empty.  The default action would be to continue rebuild the image
+            if [[ "$BASE_REVISION" = "$(git rev-parse HEAD)" ]]; then
+              # if we're on the base branch then use the parent commit
+              MERGE_BASE=$(git rev-parse HEAD~)
+            else
+              # otherwise we're on a PR, so use the most recent base commit
+              MERGE_BASE=$(git merge-base HEAD "$BASE_REVISION")
+            fi
 
-          if [[ -z "${MERGE_BASE}" ]]; then
-            echo "Finding merge base only works with full checkout, please set fetch-depth to 0, continuing ..."
+            if [[ -z "${MERGE_BASE}" ]]; then
+              echo "Finding merge base only works with full checkout, please set fetch-depth to 0, continuing ..."
+              build_image
+            fi
+
+            if ! git rev-parse "${MERGE_BASE}:${DOCKER_BUILD_DIR}"; then
+              echo "Directory '${DOCKER_BUILD_DIR}' not found in commit $MERGE_BASE, you should rebase onto a more recent commit"
+              exit 1
+            fi
+
+            PREVIOUS_DOCKER_TAG=$(git rev-parse "${MERGE_BASE}:${DOCKER_BUILD_DIR}")
+            # If no image exists but the hash is the same as the previous hash then we should error out here
+            if [[ "${PREVIOUS_DOCKER_TAG}" == "${DOCKER_TAG}" ]]; then
+              echo "WARNING: Something has gone wrong and the previous image isn't available for the merge-base of your branch"
+              echo "         Will re-build docker image to store in local cache, TTS may be longer"
+            fi
             build_image
-          fi
 
-          if ! git rev-parse "${MERGE_BASE}:${DOCKER_BUILD_DIR}"; then
-            echo "Directory '${DOCKER_BUILD_DIR}' not found in commit $MERGE_BASE, you should rebase onto a more recent commit"
-            exit 1
-          fi
+            popd
+          }
 
-          PREVIOUS_DOCKER_TAG=$(git rev-parse "${MERGE_BASE}:${DOCKER_BUILD_DIR}")
-          # If no image exists but the hash is the same as the previous hash then we should error out here
-          if [[ "${PREVIOUS_DOCKER_TAG}" == "${DOCKER_TAG}" ]]; then
-            echo "WARNING: Something has gone wrong and the previous image isn't available for the merge-base of your branch"
-            echo "         Will re-build docker image to store in local cache, TTS may be longer"
+          if [ "${ALWAYS_REBUILD:-false}" == "true" ]; then
+            build_image
+          else
+            check_if_image_exists_and_build_it_if_not
           fi
-          build_image
-
-          popd
 
     - name: Push to ECR
       if: ${{ steps.calculate-image.outputs.skip != 'true' && (inputs.always-rebuild || steps.check-and-build-image.outputs.rebuild) }}
