Retry docker build step to handle network error

diff --git a/.github/actions/calculate-docker-image/action.yml b/.github/actions/calculate-docker-image/action.yml
--- a/.github/actions/calculate-docker-image/action.yml
+++ b/.github/actions/calculate-docker-image/action.yml
@@ -147,31 +147,38 @@ runs:
         DOCKER_FORCE_PUSH: ${{ inputs.force-push }}
         DOCKER_IMAGE: ${{ steps.calculate-image.outputs.docker-image }}
         DOCKER_REGISTRY: ${{ inputs.docker-registry }}
-      run: |
-        set -x
-        set +e
+      # NB: Retry here as this step frequently fails with network error downloading various stuffs
+      uses: nick-fields/retry@v3.0.0
+      with:
+        shell: bash
+        timeout_minutes: 15
+        max_attempts: 3
+        retry_wait_seconds: 90
+        command: |
+          set -x
+          set +e
 
-        login() {
-          aws ecr get-login-password --region us-east-1 | docker login -u AWS --password-stdin "$1"
-        }
+          login() {
+            aws ecr get-login-password --region us-east-1 | docker login -u AWS --password-stdin "$1"
+          }
 
-        retry () {
-          $*  || (sleep 1 && $*) || (sleep 2 && $*)
-        }
+          retry () {
+            $*  || (sleep 1 && $*) || (sleep 2 && $*)
+          }
 
-        retry login "${DOCKER_REGISTRY}"
+          retry login "${DOCKER_REGISTRY}"
 
-        set -e
+          set -e
 
-        IMAGE_NAME=$(echo ${DOCKER_IMAGE#"${DOCKER_REGISTRY}/${REPO_NAME}/"} | awk -F '[:,]' '{print $1}')
-        # Build new image
-        ./build.sh "${IMAGE_NAME}" -t "${DOCKER_IMAGE}"
+          IMAGE_NAME=$(echo ${DOCKER_IMAGE#"${DOCKER_REGISTRY}/${REPO_NAME}/"} | awk -F '[:,]' '{print $1}')
+          # Build new image
+          ./build.sh "${IMAGE_NAME}" -t "${DOCKER_IMAGE}"
 
-        if [ "${DOCKER_PUSH:-false}" == "true" ]; then
-          # Only push if docker image doesn't exist already
-          if ! docker manifest inspect "${DOCKER_IMAGE}" >/dev/null 2>/dev/null || [ "${DOCKER_FORCE_PUSH:-false}" == "true" ]; then
-            docker push "${DOCKER_IMAGE}"
+          if [ "${DOCKER_PUSH:-false}" == "true" ]; then
+            # Only push if docker image doesn't exist already
+            if ! docker manifest inspect "${DOCKER_IMAGE}" >/dev/null 2>/dev/null || [ "${DOCKER_FORCE_PUSH:-false}" == "true" ]; then
+              docker push "${DOCKER_IMAGE}"
+            fi
+            # Check that upload was successfull or that image already exists
+            docker manifest inspect "${DOCKER_IMAGE}"
           fi
-          # Check that upload was successfull or that image already exists
-          docker manifest inspect "${DOCKER_IMAGE}"
-        fi
