test build script

diff --git a/.github/workflows/build_wheels_windows_x64_test.yml b/.github/workflows/build_wheels_windows_x64_test.yml
--- a/.github/workflows/build_wheels_windows_x64_test.yml
+++ b/.github/workflows/build_wheels_windows_x64_test.yml
@@ -28,6 +28,16 @@ on:
         required: false
         type: string
 
+env:
+  DOWNLOADS_DIR: c:\temp\downloads\
+  DEPENDENCIES_DIR: c:\temp\dependencies\
+  SCRIPTS_DIR: test-infra\\.github\\scripts\\winx64test
+  SRC_DIR: src\\${{ inputs.repository_name }}
+  PYTHON_VERSION: ${{ inputs.python_version }}
+  MSVC_VERSION: ${{ inputs.msvc_version }}
+  BUILD_TYPE: ${{ inputs.build_type }}
+  BUILD_VERSION : ${{ inputs.build_version }}
+
 permissions:
   id-token: write
   contents: read
@@ -37,17 +47,6 @@ jobs:
     runs-on: windows-latest
     name: Build wheel
     steps:
-      - name: Set up environment variables
-        id: env_vars
-        run: |
-          echo "DOWNLOADS_DIR=c:\\temp\\downloads\\$(basename '${{ inputs.repository_name }}')" >> $GITHUB_ENV
-          echo "DEPENDENCIES_DIR=c:\\temp\\dependencies\\$(basename '${{ inputs.repository_name }}')" >> $GITHUB_ENV
-          echo "SRC_DIR=src\\${{ inputs.repository_name }}" >> $GITHUB_ENV
-          echo "SCRIPTS_DIR=test-infra\\.github\\scripts\\winx64test" >> $GITHUB_ENV
-          echo "PYTHON_VERSION=${{ inputs.python_version }}" >> $GITHUB_ENV
-          echo "MSVC_VERSION=${{ inputs.msvc_version }}" >> $GITHUB_ENV
-          echo "BUILD_TYPE=${{ inputs.build_type }}" >> $GITHUB_ENV
-          echo "BUILD_VERSION=${{ inputs.build_version }}" >> $GITHUB_ENV
       - name: Checkout test-infra Repository
         uses: actions/checkout@v4
         with:
@@ -59,23 +58,22 @@ jobs:
         with:
             repository: ${{ inputs.repository_name }}
             ref: ${{ inputs.repository_branch }}
-            path: src/${{ inputs.repository_name }}  # Stores it in 'src/{repository_name}/'
+            path: src/${{ inputs.repository_name }}
             submodules: recursive
-      - name: Debug Paths
-        shell: bash
-        run: |
-          echo "SCRIPTS_DIR: $SCRIPTS_DIR"
-          ls -l "$SCRIPTS_DIR" || echo "SCRIPTS_DIR does not exist"
+      # - name: Debug Paths
+      #   shell: bash
+      #   run: |
+      #     echo "SCRIPTS_DIR: $SCRIPTS_DIR"
+      #     ls -l "$SCRIPTS_DIR" || echo "SCRIPTS_DIR does not exist"
       
-          echo "Checking test-infra\\.github\\scripts\\winx64test\\ directory explicitly:"
-          ls -l test-infra\\.github\\scripts\\winx64test\\ || echo "Explicit path check failed"
+      #     echo "Checking test-infra\\.github\\scripts\\winx64test\\ directory explicitly:"
+      #     ls -l test-infra\\.github\\scripts\\winx64test\\ || echo "Explicit path check failed"
 
-          echo "SRC_DIR: $SRC_DIR"
-          ls -l "$SRC_DIR" || echo "SRC_DIR does not exist"
+      #     echo "SRC_DIR: $SRC_DIR"
+      #     ls -l "$SRC_DIR" || echo "SRC_DIR does not exist"
 
-          echo "Checking src\\pytorch\\vision directory explicitly:"
-          ls -l src\\pytorch\\vision || echo "Explicit path check failed"
-
+      #     echo "Checking src\\pytorch\\vision directory explicitly:"
+      #     ls -l src\\pytorch\\vision || echo "Explicit path check failed"
       # - name: Run Bootstrap Git Script
       #   shell: cmd
       #   run: |
@@ -99,13 +97,6 @@ jobs:
       # #     run-id: ${{ inputs.pytorch_build_run_id }}
       # #     name: ${{ inputs.pytorch_build_artifact_name }}
       # #     path: ${{ env.DOWNLOADS_DIR }}
-      # - name: Git checkout repo ${{ inputs.repository_name }}
-      #   uses: actions/checkout@v4
-      #   with:
-      #     repository: ${{ inputs.repository_name }}
-      #     ref: ${{ inputs.repository_branch }}
-      #     path: ${{ env.SRC_DIR }}
-      #     submodules: recursive
       - name: Call Build Script
         shell: bash
         run: |
