add debug path step

diff --git a/.github/workflows/build_wheels_windows_x64_test.yml b/.github/workflows/build_wheels_windows_x64_test.yml
--- a/.github/workflows/build_wheels_windows_x64_test.yml
+++ b/.github/workflows/build_wheels_windows_x64_test.yml
@@ -31,7 +31,7 @@ on:
 env:
   DOWNLOADS_DIR: c:\temp\downloads\${{ inputs.repository_name }}
   DEPENDENCIES_DIR: c:\temp\dependencies\${{ inputs.repository_name }}
-  SCRIPTS_DIR:  .test-infra\.github\scripts\winx64test\
+  SCRIPTS_DIR: .github\scripts\winx64test\
   SRC_DIR: src\${{ inputs.repository_name }}
   PYTHON_VERSION: ${{ inputs.python_version }}
   MSVC_VERSION: ${{ inputs.msvc_version }}
@@ -47,6 +47,20 @@ jobs:
     runs-on: windows-latest
     name: Build wheel
     steps:
+      - name: Debug Paths
+        shell: bash
+        run: |
+          echo "Current Directory:"
+          pwd  # Print current directory
+      
+          echo "Listing contents of current directory:"
+          ls -l 
+      
+          echo "SCRIPTS_DIR: $SCRIPTS_DIR"
+          ls -l "$SCRIPTS_DIR" || echo "SCRIPTS_DIR does not exist"
+      
+          echo "Checking .test-infra/.github/scripts/winx64test directory explicitly:"
+          ls -l .test-infra/.github/scripts/winx64test || echo "Explicit path check failed"
       - name: Git checkout workflow
         uses: actions/checkout@v4
       - name: Bootstrap Git
