Use env scripts for Windows binary build clean (#5704)
Cause the binary build clean also need to import torch.
Works for https://github.com/pytorch/pytorch/issues/114850

diff --git a/.github/workflows/build_wheels_windows.yml b/.github/workflows/build_wheels_windows.yml
--- a/.github/workflows/build_wheels_windows.yml
+++ b/.github/workflows/build_wheels_windows.yml
@@ -147,7 +147,16 @@ jobs:
         working-directory: ${{ inputs.repository }}
         run: |
           source "${BUILD_ENV_FILE}"
-          ${CONDA_RUN} python setup.py clean
+          if [[ -z "${ENV_SCRIPT}" ]]; then
+            ${CONDA_RUN} python setup.py clean
+          else
+            if [[ ! -f ${ENV_SCRIPT} ]]; then
+              echo "::error::Specified env-script file (${ENV_SCRIPT}) not found"
+              exit 1
+            else
+              ${CONDA_RUN} ${ENV_SCRIPT} python setup.py clean
+            fi
+          fi
       - name: Build the wheel (bdist_wheel)
         working-directory: ${{ inputs.repository }}
         env:
@@ -167,12 +176,7 @@ jobs:
           if [[ -z "${ENV_SCRIPT}" ]]; then
             ${CONDA_RUN} python setup.py bdist_wheel
           else
-            if [[ ! -f ${ENV_SCRIPT} ]]; then
-              echo "::error::Specified env-script file (${ENV_SCRIPT}) not found"
-              exit 1
-            else
-              ${CONDA_RUN} ${ENV_SCRIPT} python setup.py bdist_wheel ${BUILD_PARAMS}
-            fi
+            ${CONDA_RUN} ${ENV_SCRIPT} python setup.py bdist_wheel ${BUILD_PARAMS}
           fi
       - name: Run post-script
         working-directory: ${{ inputs.repository }}
@@ -195,7 +199,7 @@ jobs:
           ${CONDA_RUN} pip install "${{ inputs.repository }}/dist/$WHEEL_NAME"
           if [[ ! -f "${{ inputs.repository }}"/${SMOKE_TEST_SCRIPT} ]]; then
             echo "${{ inputs.repository }}/${SMOKE_TEST_SCRIPT} not found"
-            ${CONDA_RUN} python -c "import ${PACKAGE_NAME}; print('package version is ', ${PACKAGE_NAME}.__version__)"
+            ${CONDA_RUN} ${ENV_SCRIPT} python -c "import ${PACKAGE_NAME}; print('package version is ', ${PACKAGE_NAME}.__version__)"
           else
             echo "${{ inputs.repository }}/${SMOKE_TEST_SCRIPT} found"
             ${CONDA_RUN} ${ENV_SCRIPT} python "${{ inputs.repository }}/${SMOKE_TEST_SCRIPT}"
