slashes test

diff --git a/.github/workflows/build_wheels_windows_x64_test.yml b/.github/workflows/build_wheels_windows_x64_test.yml
--- a/.github/workflows/build_wheels_windows_x64_test.yml
+++ b/.github/workflows/build_wheels_windows_x64_test.yml
@@ -31,7 +31,7 @@ on:
 env:
   DOWNLOADS_DIR: c:\temp\downloads\${{ inputs.repository_name }}
   DEPENDENCIES_DIR: c:\temp\dependencies\${{ inputs.repository_name }}
-  SCRIPTS_DIR: test-infra\.github\scripts\winx64test\
+  SCRIPTS_DIR: test-infra\\.github\\scripts\\winx64test\\
   SRC_DIR: src\${{ inputs.repository_name }}
   PYTHON_VERSION: ${{ inputs.python_version }}
   MSVC_VERSION: ${{ inputs.msvc_version }}
@@ -65,9 +65,9 @@ jobs:
           echo "SCRIPTS_DIR: $SCRIPTS_DIR"
           ls -l "$SCRIPTS_DIR" || echo "SCRIPTS_DIR does not exist"
       
-          echo "Checking test-infra\.github\scripts\winx64test\ directory explicitly:"
-          ls -l test-infra\.github\scripts\winx64test\ || echo "Explicit path check failed"
-          
+          echo "Checking test-infra\\.github\\scripts\\winx64test\\ directory explicitly:"
+          ls -l test-infra\\.github\\scripts\winx64test\\ || echo "Explicit path check failed"
+
       - name: Git checkout workflow
         uses: actions/checkout@v4
       - name: Bootstrap Git
@@ -76,6 +76,7 @@ jobs:
           echo "SCRIPTS_DIR: $SCRIPTS_DIR"
           ls -l "$SCRIPTS_DIR" || echo "SCRIPTS_DIR does not exist"
           cmd //c "${{ env.SCRIPTS_DIR }}\bootstrap_git.bat"
+          cmd //c "test-infra\\.github\\scripts\winx64test\\bootstrap_git.bat"
       - name: Bootstrap Python
         run: |
           echo "SCRIPTS_DIR: $SCRIPTS_DIR"
