Add torchtext to win wheels

diff --git a/.github/workflows/build_wheels_windows.yml b/.github/workflows/build_wheels_windows.yml
--- a/.github/workflows/build_wheels_windows.yml
+++ b/.github/workflows/build_wheels_windows.yml
@@ -27,8 +27,20 @@ on:
         description: "Pre script to run prior to build"
         default: ""
         type: string
+      env-script:
+        description: "Script to setup environment variables for the build"
+        default: ""
+        type: string
       post-script:
         description: "Post script to run prior to build"
+        default: ""
+        type: string
+      smoke-test-script:
+        description: "Script for Smoke Test for a specific domain"
+        default: ""
+        type: string
+      package-name:
+        description: "Name of the actual python package that is imported"
         default: ""
         type: string
       runner-type:
@@ -91,9 +103,20 @@ jobs:
           ${CONDA_RUN} python setup.py clean
       - name: Build the wheel (bdist_wheel)
         working-directory: ${{ inputs.repository }}
+        env:
+          ENV_SCRIPT: ${{ inputs.env-script }}
         run: |
           source "${BUILD_ENV_FILE}"
-          ${CONDA_RUN} python setup.py bdist_wheel
+          if [[ -z "${ENV_SCRIPT}" ]]; then
+            ${CONDA_RUN} python setup.py bdist_wheel
+          else
+            if [[ ! -f ${ENV_SCRIPT} ]]; then
+              echo "::error::Specified env-script file (${ENV_SCRIPT}) not found"
+              exit 1
+            else
+              ${CONDA_RUN} ${ENV_SCRIPT} python setup.py bdist_wheel
+            fi
+          fi
       - name: Upload wheel to GitHub
         uses: actions/upload-artifact@v3
         with:
@@ -111,6 +134,24 @@ jobs:
           else
             ${CONDA_RUN} bash "${POST_SCRIPT}"
           fi
+      - name: Run Primitive Smoke Tests
+        env:
+          PACKAGE_NAME: ${{ inputs.package-name }}
+          SMOKE_TEST_SCRIPT: ${{ inputs.smoke-test-script }}
+        run: |
+          source "${BUILD_ENV_FILE}"
+          WHEEL_NAME=$(ls "${{ inputs.repository }}/dist/")
+          echo "$WHEEL_NAME"
+          ${CONDA_RUN} pip install "${{ inputs.repository }}/dist/$WHEEL_NAME"
+          if [[ ! -f "${{ inputs.repository }}"/${SMOKE_TEST_SCRIPT} ]]; then
+            echo "${{ inputs.repository }}/${SMOKE_TEST_SCRIPT} not found"
+            ${CONDA_RUN} python -c "import ${PACKAGE_NAME}; print('package version is ', ${PACKAGE_NAME}.__version__)"
+          else
+            echo "${{ inputs.repository }}/${SMOKE_TEST_SCRIPT} found"
+            export LD_LIBRARY_PATH="{LD_LIBRARY_PATH}:${{ inputs.repository }}/third_party/ffmpeg/lib"
+            ${CONDA_RUN} python "${{ inputs.repository }}/${SMOKE_TEST_SCRIPT}"
+          fi
+
       # TODO: Figure out upload method to s3
 
 concurrency:
