change ops order

diff --git a/.github/workflows/build_wheels_windows_x64_test.yml b/.github/workflows/build_wheels_windows_x64_test.yml
--- a/.github/workflows/build_wheels_windows_x64_test.yml
+++ b/.github/workflows/build_wheels_windows_x64_test.yml
@@ -47,22 +47,22 @@ jobs:
     runs-on: windows-latest
     name: Build wheel
     steps:
+      - name: Git checkout workflow
+        uses: actions/checkout@v4
       - name: Checkout test-infra repository
         uses: actions/checkout@v4
         with:
           repository: alinpahontu2912/test-infra 
           ref: x64windows_test
           path: test-infra
-      # - name: Debug Paths
-      #   shell: bash
-      #   run: |
-      #     echo "SCRIPTS_DIR: $SCRIPTS_DIR"
-      #     ls -l "$SCRIPTS_DIR" || echo "SCRIPTS_DIR does not exist"
+      - name: Debug Paths
+        shell: bash
+        run: |
+          echo "SCRIPTS_DIR: $SCRIPTS_DIR"
+          ls -l "$SCRIPTS_DIR" || echo "SCRIPTS_DIR does not exist"
       
-      #     echo "Checking test-infra\\.github\\scripts\\winx64test\\ directory explicitly:"
-      #     ls -l test-infra\\.github\\scripts\\winx64test\\ || echo "Explicit path check failed"
-      - name: Git checkout workflow
-        uses: actions/checkout@v4
+          echo "Checking test-infra\\.github\\scripts\\winx64test\\ directory explicitly:"
+          ls -l test-infra\\.github\\scripts\\winx64test\\ || echo "Explicit path check failed"
       - name: Bootstrap Git
         shell: bash
         run: |
@@ -71,7 +71,7 @@ jobs:
       
           echo "Checking test-infra\\.github\\scripts\\winx64test\\ directory explicitly:"
           ls -l test-infra\\.github\\scripts\\winx64test\\ || echo "Explicit path check failed"
-          cmd //c "test-infra\\.github\\scripts\\winx64test\\bootstrap_git.bat"
+          cmd //c "${{ env.SCRIPTS_DIR }}\\bootstrap_git.bat"
       - name: Bootstrap Git 2 test
         shell: bash
         run: |
