ci: Switch generic linux_job to use conda images (#877)
conda images are better since conda automatically comes with all of the
python versions and people tend to like conda better for test
environments

Signed-off-by: Eli Uriegas <eliuriegas@fb.com>

diff --git a/.github/workflows/linux_job.yml b/.github/workflows/linux_job.yml
--- a/.github/workflows/linux_job.yml
+++ b/.github/workflows/linux_job.yml
@@ -51,7 +51,7 @@ on:
 jobs:
   job:
     env:
-      DOCKER_IMAGE: pytorch/manylinux-builder:${{ inputs.gpu-arch-type }}${{ inputs.gpu-arch-version }}
+      DOCKER_IMAGE: pytorch/conda-builder:${{ inputs.gpu-arch-type }}${{ inputs.gpu-arch-version }}
       REPOSITORY: ${{ inputs.repository || github.repository }}
       SCRIPT: ${{ inputs.script }}
     runs-on: ${{ inputs.runner }}
@@ -98,7 +98,13 @@ jobs:
       - name: Run script in container
         working-directory: ${{ inputs.repository }}
         run: |
-          echo "${SCRIPT}" >> "${RUNNER_TEMP}/exec_script"
+          {
+            echo "#!/usr/bin/env bash";
+            echo "set -eou pipefail";
+            # shellcheck disable=SC2016
+            echo 'eval "$(conda shell.bash hook)"';
+            echo "${SCRIPT}";
+          } > "${RUNNER_TEMP}/exec_script"
           chmod +x "${RUNNER_TEMP}/exec_script"
           # detached container should get cleaned up by teardown_ec2_linux
           # shellcheck disable=SC2086,SC2090
