show what is happening at each step

diff --git a/.github/workflows/linux_job.yml b/.github/workflows/linux_job.yml
--- a/.github/workflows/linux_job.yml
+++ b/.github/workflows/linux_job.yml
@@ -150,7 +150,7 @@ jobs:
           set -ex
           {
             echo "#!/usr/bin/env bash";
-            echo "set -eou pipefail";
+            echo "set -exou pipefail";
             # shellcheck disable=SC2016
             echo 'eval "$(conda shell.bash hook)"';
             echo "${SCRIPT}";
