Added the 'Run script' step

diff --git a/.github/workflows/linux_job.yml b/.github/workflows/linux_job.yml
--- a/.github/workflows/linux_job.yml
+++ b/.github/workflows/linux_job.yml
@@ -98,6 +98,11 @@ on:
 jobs:
   job:
     name: ${{ inputs.job-name }}
+    env:
+      REPOSITORY: ${{ inputs.repository || github.repository }}
+      # Will be blank outside of this
+      PR_NUMBER: ${{ github.event.pull_request.number }}
+      SCRIPT: ${{ inputs.script }}
     runs-on: ${{ inputs.runner }}
     container:
       image: ${{ inputs.docker-image }}
@@ -164,22 +169,48 @@ jobs:
           binary-matrix: ${{ inputs.binary-matrix }}
           target-os: "linux"
 
-      - name: Run script in container
-#        if: ${{ inputs.run-with-docker == true }}
+#      - name: Run script in container
+##        if: ${{ inputs.run-with-docker == true }}
+#        continue-on-error: ${{ inputs.continue-on-error }}
+#        working-directory: ${{ inputs.repository }}
+#        env:
+#          ALL_SECRETS: ${{ toJSON(secrets) }}
+##          DOCKER_IMAGE: ${{ steps.calculate-docker-image.outputs.docker-image }}
+#        run: |
+#          set -ex
+#          {
+#            echo "#!/usr/bin/env bash";
+#            echo "set -eou pipefail";
+#            # shellcheck disable=SC2016
+#            echo 'eval "$(conda shell.bash hook)"';
+#            echo "set -x";
+#            echo "${SCRIPT}";
+#          } > "${RUNNER_TEMP}/exec_script"
+#          chmod +x "${RUNNER_TEMP}/exec_script"
+#          python3 "${{ github.workspace }}/test-infra/.github/scripts/run_with_env_secrets.py" "${{ inputs.secrets-env }}"
+          
+
+      - name: Run script outside container
+#        if: ${{ inputs.run-with-docker == false }}
         continue-on-error: ${{ inputs.continue-on-error }}
         working-directory: ${{ inputs.repository }}
         env:
           ALL_SECRETS: ${{ toJSON(secrets) }}
-#          DOCKER_IMAGE: ${{ steps.calculate-docker-image.outputs.docker-image }}
         run: |
-          set -ex
           {
             echo "#!/usr/bin/env bash";
-            echo "set -eou pipefail"; 
-            # shellcheck disable=SC2016
-            echo 'eval "$(conda shell.bash hook)"';
-            echo "set -x";
+            echo "set -eou pipefail";
+            # Source conda so it's available to the script environment
             echo "${SCRIPT}";
           } > "${RUNNER_TEMP}/exec_script"
-          chmod +x "${RUNNER_TEMP}/exec_script"
-          python3 "${{ github.workspace }}/test-infra/.github/scripts/run_with_env_secrets.py" "${{ inputs.secrets-env }}"
+          # The GITHUB_WORKFLOW env var contains the name of the workflow
+          # defined at the top of the workflow file. Unfortunately this is not
+          # enclosed in quotes in the env file, so simply eval-ing each line in
+          # the file will fail. As a workaround, we eval all env vars except
+          # for GITHUB_WORKFLOW here.
+          while read -r line; do
+            if [[ "${line}" != "GITHUB_WORKFLOW="* ]]; then
+              eval "export ${line}"
+            fi
+          done < "${RUNNER_TEMP}/github_env_${GITHUB_RUN_ID}"
+          bash "${RUNNER_TEMP}/exec_script"
