add some initialization to the script
Signed-off-by: Eli Uriegas <eliuriegas@fb.com>

diff --git a/.github/workflows/linux_job.yml b/.github/workflows/linux_job.yml
--- a/.github/workflows/linux_job.yml
+++ b/.github/workflows/linux_job.yml
@@ -98,6 +98,9 @@ jobs:
       - name: Run script in container
         working-directory: ${{ inputs.repository }}
         run: |
+          echo "#!/usr/bin/env bash" > "${RUNNER_TEMP}/exec_script"
+          echo "set -eou pipefail" >> "${RUNNER_TEMP}/exec_script"
+          echo "conda init" >> "${RUNNER_TEMP}/exec_script"
           echo "${SCRIPT}" >> "${RUNNER_TEMP}/exec_script"
           chmod +x "${RUNNER_TEMP}/exec_script"
           # detached container should get cleaned up by teardown_ec2_linux
