Test

diff --git a/.github/workflows/linux_job.yml b/.github/workflows/linux_job.yml
--- a/.github/workflows/linux_job.yml
+++ b/.github/workflows/linux_job.yml
@@ -99,16 +99,16 @@ on:
 jobs:
   job:
     name: ${{ inputs.job-name }}
-    env:
-      DOCKER_IMAGE: >-
-        ${{ inputs.docker-image == 'pytorch/conda-builder' && format('pytorch/conda-builder:{0}{1}',
-                                                                      inputs.gpu-arch-type,
-                                                                      inputs.gpu-arch-version)
-                                                           || inputs.docker-image }}
-      REPOSITORY: ${{ inputs.repository || github.repository }}
-      # Will be blank outside of this
-      PR_NUMBER: ${{ github.event.pull_request.number }}
-      SCRIPT: ${{ inputs.script }}
+#    env:
+#      DOCKER_IMAGE: >-
+#        ${{ inputs.docker-image == 'pytorch/conda-builder' && format('pytorch/conda-builder:{0}{1}',
+#                                                                      inputs.gpu-arch-type,
+#                                                                      inputs.gpu-arch-version)
+#                                                           || inputs.docker-image }}
+#      REPOSITORY: ${{ inputs.repository || github.repository }}
+#      # Will be blank outside of this
+#      PR_NUMBER: ${{ github.event.pull_request.number }}
+#      SCRIPT: ${{ inputs.script }}
     runs-on: ${{ inputs.runner }}
     # TODO: Eventually this should run in a container, we need to make a container that matches up
     #       with the users for our self hosted runner infra since using actions/checkout with a root
@@ -118,213 +118,220 @@ jobs:
     container:
       image: ${{ inputs.docker-image }}
     steps:
-      - name: Check workplace
-        run: |
-          uname -a
-          ls -lha
-          pwd
-          whoami
-      - name: Clean workspace
-        env:
-          NO_SUDO: ${{ inputs.no-sudo }}
-        run: |
-          set -euxo pipefail
-          if [[ "${NO_SUDO}" == "false" ]]; then
-            echo "::group::Cleanup with-sudo debug output"
-            sudo rm -rfv "${GITHUB_WORKSPACE}"
-          else
-            echo "::group::Cleanup no-sudo debug output"
-            rm -rfv "${GITHUB_WORKSPACE}"
-          fi
+      - name: Checkout code
+        uses: actions/checkout@v2
 
-          mkdir -p "${GITHUB_WORKSPACE}"
-          echo "::endgroup::"
+      - name: Run a command inside the Docker container
+        run: echo "Hello from the container!"
 
-      - name: Checkout repository (${{ inputs.test-infra-repository }}@${{ inputs.test-infra-ref }})
-        uses: actions/checkout@v3
-        with:
-          # Support the use case where we need to checkout someone's fork
-          repository: ${{ inputs.test-infra-repository }}
-          ref: ${{ inputs.test-infra-ref }}
-          path: test-infra
-
-          # PyTorch, the primary target for this job template, heavily
-          # relies on submodules. Clone them by default to avoid
-          # surprises.
-          submodules: 'recursive'
-
-      - name: Setup Linux
-        uses: ./test-infra/.github/actions/setup-linux
-
-#      - name: Setup SSH
-#        uses: ./test-infra/.github/actions/setup-ssh
+#    steps:
+#      - name: Check workplace
+#        run: |
+#          uname -a
+#          ls -lha
+#          pwd
+#          whoami
+#      - name: Clean workspace
+#        env:
+#          NO_SUDO: ${{ inputs.no-sudo }}
+#        run: |
+#          set -euxo pipefail
+#          if [[ "${NO_SUDO}" == "false" ]]; then
+#            echo "::group::Cleanup with-sudo debug output"
+#            sudo rm -rfv "${GITHUB_WORKSPACE}"
+#          else
+#            echo "::group::Cleanup no-sudo debug output"
+#            rm -rfv "${GITHUB_WORKSPACE}"
+#          fi
+#
+#          mkdir -p "${GITHUB_WORKSPACE}"
+#          echo "::endgroup::"
+#
+#      - name: Checkout repository (${{ inputs.test-infra-repository }}@${{ inputs.test-infra-ref }})
+#        uses: actions/checkout@v3
 #        with:
-#          github-secret: ${{ github.token }}
-
-      - name: Checkout repository (${{ inputs.repository || github.repository }}@${{ inputs.ref }})
-        uses: actions/checkout@v3
-        with:
-          # Support the use case where we need to checkout someone's fork
-          repository: ${{ inputs.repository || github.repository }}
-          ref: ${{ inputs.ref || github.ref }}
-          path: ${{ inputs.repository || github.repository }}
-          fetch-depth: ${{ inputs.fetch-depth }}
-          submodules: ${{ inputs.submodules }}
-
-      - name: Calculate docker image
-        id: calculate-docker-image
-        uses: ./test-infra/.github/actions/calculate-docker-image
-        with:
-          docker-image-name: ${{ env.DOCKER_IMAGE }}
-          docker-build-dir: ${{ inputs.docker-build-dir }}
-          # This needs to be where the repository is checked out
-          working-directory: ${{ inputs.repository || github.repository }}
-
-      - name: Pull docker image
-        uses: ./test-infra/.github/actions/pull-docker-image
-        with:
-          docker-image: ${{ steps.calculate-docker-image.outputs.docker-image }}
-
-      - name: Download artifacts (if any)
-        uses: actions/download-artifact@v3
-        if: ${{ inputs.download-artifact != '' }}
-        with:
-          name: ${{ inputs.download-artifact }}
-          path: ${{ runner.temp }}/artifacts/
-
-      - name: Export matrix variables (if any)
-        uses: ./test-infra/.github/actions/export-matrix-variables
-        if: ${{ inputs.binary-matrix != '' }}
-        with:
-          binary-matrix: ${{ inputs.binary-matrix }}
-          target-os: "linux"
-
-      - name: Run script in container
-        if: ${{ inputs.run-with-docker == true }}
-        continue-on-error: ${{ inputs.continue-on-error }}
-        working-directory: ${{ inputs.repository }}
-        env:
-          ALL_SECRETS: ${{ toJSON(secrets) }}
-          DOCKER_IMAGE: ${{ steps.calculate-docker-image.outputs.docker-image }}
-        run: |
-          set -ex
-          {
-            echo "#!/usr/bin/env bash";
-            echo "set -eou pipefail";
-            # shellcheck disable=SC2016
-            echo 'eval "$(conda shell.bash hook)"';
-            echo "set -x";
-            echo "${SCRIPT}";
-          } > "${RUNNER_TEMP}/exec_script"
-          chmod +x "${RUNNER_TEMP}/exec_script"
-          python3 "${{ github.workspace }}/test-infra/.github/scripts/run_with_env_secrets.py" "${{ inputs.secrets-env }}"
-
-      - name: Run script outside container
-        if: ${{ inputs.run-with-docker == false }}
-        continue-on-error: ${{ inputs.continue-on-error }}
-        working-directory: ${{ inputs.repository }}
-        env:
-          ALL_SECRETS: ${{ toJSON(secrets) }}
-        run: |
-          {
-            echo "#!/usr/bin/env bash";
-            echo "set -eou pipefail";
-            # Source conda so it's available to the script environment
-            echo "${SCRIPT}";
-          } > "${RUNNER_TEMP}/exec_script"
-          # The GITHUB_WORKFLOW env var contains the name of the workflow
-          # defined at the top of the workflow file. Unfortunately this is not
-          # enclosed in quotes in the env file, so simply eval-ing each line in
-          # the file will fail. As a workaround, we eval all env vars except
-          # for GITHUB_WORKFLOW here.
-          while read -r line; do
-            if [[ "${line}" != "GITHUB_WORKFLOW="* ]]; then
-              eval "export ${line}"
-            fi
-          done < "${RUNNER_TEMP}/github_env_${GITHUB_RUN_ID}"
-          bash "${RUNNER_TEMP}/exec_script"
-
-      - name: Surface failing tests
-        if: always()
-        uses: pmeier/pytest-results-action@v0.3.0
-        with:
-          path: ${{ env.RUNNER_TEST_RESULTS_DIR }}
-          fail-on-empty: false
-
-      - name: Chown repository directory
-        if: always()
-        uses: ./test-infra/.github/actions/chown-directory
-        with:
-          directory: ${{ github.workspace }}/${{ env.repository }}
-          ALPINE_IMAGE: ${{ inputs.runner == 'linux.arm64.2xlarge' && 'arm64v8/alpine' || '308535385114.dkr.ecr.us-east-1.amazonaws.com/tool/alpine' }}
-
-      - name: Chown runner temp
-        if: always()
-        uses: ./test-infra/.github/actions/chown-directory
-        with:
-          directory: ${{ env.RUNNER_TEMP }}
-          ALPINE_IMAGE: ${{ inputs.runner == 'linux.arm64.2xlarge' && 'arm64v8/alpine' || '308535385114.dkr.ecr.us-east-1.amazonaws.com/tool/alpine' }}
-
-      - name: Prepare artifacts for upload
-        working-directory: ${{ inputs.repository }}
-        id: check-artifacts
-        env:
-          UPLOAD_ARTIFACT_NAME: ${{ inputs.upload-artifact }}
-        run: |
-          # Only do these steps if we actually want to upload an artifact
-          if [[ -n "${UPLOAD_ARTIFACT_NAME}" ]]; then
-            # If the default execution path is followed then we should get a wheel in the dist/ folder
-            # attempt to just grab whatever is in there and scoop it all up
-            if find "dist/" -name "*.whl" >/dev/null 2>/dev/null; then
-              mv -v dist/*.whl "${RUNNER_ARTIFACT_DIR}/"
-            fi
-            # Set to fail upload step if there are no files for upload and expected files for upload
-            echo 'if-no-files-found=error' >> "${GITHUB_OUTPUT}"
-          fi
-
-          upload_docs=0
-          # Check if there are files in the documentation folder to upload, note that
-          # empty folders do not count
-          if find "${RUNNER_DOCS_DIR}" -mindepth 1 -maxdepth 1 -type f | read -r; then
-            # TODO: Add a check here to test if on ec2 because if we're not on ec2 then this
-            # upload will probably not work correctly
-            upload_docs=1
-          fi
-          echo "upload-docs=${upload_docs}" >> "${GITHUB_OUTPUT}"
-
-      - name: Upload artifacts to GitHub (if any)
-        uses: actions/upload-artifact@v3
-        if: ${{ inputs.upload-artifact != '' }}
-        with:
-          name: ${{ inputs.upload-artifact }}
-          path: ${{ runner.temp }}/artifacts/
-          if-no-files-found: ${{ steps.check-artifacts.outputs.if-no-files-found }}
-
-      - name: Upload documentation to S3 (if any)
-        uses: seemethere/upload-artifact-s3@v5
-        if: ${{ steps.check-artifacts.outputs.upload-docs == 1 && github.event.pull_request.number != '' }}
-        with:
-          retention-days: 14
-          s3-bucket: doc-previews
-          if-no-files-found: error
-          path: ${{ env.RUNNER_DOCS_DIR }}
-          # ${{ env.repository }} is $OWNER/$REPO
-          s3-prefix: ${{ env.REPOSITORY }}/${{ github.event.pull_request.number }}
-
-      - name: Teardown Linux
-        if: ${{ always() }}
-        uses: ./test-infra/.github/actions/teardown-linux
-
-      - name: Clean workspace after tear down
-        if: ${{ always() }}
-        env:
-          NO_SUDO: ${{ inputs.no-sudo }}
-          REPOSITORY: ${{ inputs.repository || github.repository }}
-        run: |
-          set +e
-          if [[ "${NO_SUDO}" == "false" ]]; then
-            sudo rm -rf "${GITHUB_WORKSPACE:?}/${REPOSITORY:?}"
-          else
-            rm -rf "${GITHUB_WORKSPACE:?}/${REPOSITORY:?}"
-          fi
-          set -e
+#          # Support the use case where we need to checkout someone's fork
+#          repository: ${{ inputs.test-infra-repository }}
+#          ref: ${{ inputs.test-infra-ref }}
+#          path: test-infra
+#
+#          # PyTorch, the primary target for this job template, heavily
+#          # relies on submodules. Clone them by default to avoid
+#          # surprises.
+#          submodules: 'recursive'
+#
+#      - name: Setup Linux
+#        uses: ./test-infra/.github/actions/setup-linux
+#
+##      - name: Setup SSH
+##        uses: ./test-infra/.github/actions/setup-ssh
+##        with:
+##          github-secret: ${{ github.token }}
+#
+#      - name: Checkout repository (${{ inputs.repository || github.repository }}@${{ inputs.ref }})
+#        uses: actions/checkout@v3
+#        with:
+#          # Support the use case where we need to checkout someone's fork
+#          repository: ${{ inputs.repository || github.repository }}
+#          ref: ${{ inputs.ref || github.ref }}
+#          path: ${{ inputs.repository || github.repository }}
+#          fetch-depth: ${{ inputs.fetch-depth }}
+#          submodules: ${{ inputs.submodules }}
+#
+#      - name: Calculate docker image
+#        id: calculate-docker-image
+#        uses: ./test-infra/.github/actions/calculate-docker-image
+#        with:
+#          docker-image-name: ${{ env.DOCKER_IMAGE }}
+#          docker-build-dir: ${{ inputs.docker-build-dir }}
+#          # This needs to be where the repository is checked out
+#          working-directory: ${{ inputs.repository || github.repository }}
+#
+#      - name: Pull docker image
+#        uses: ./test-infra/.github/actions/pull-docker-image
+#        with:
+#          docker-image: ${{ steps.calculate-docker-image.outputs.docker-image }}
+#
+#      - name: Download artifacts (if any)
+#        uses: actions/download-artifact@v3
+#        if: ${{ inputs.download-artifact != '' }}
+#        with:
+#          name: ${{ inputs.download-artifact }}
+#          path: ${{ runner.temp }}/artifacts/
+#
+#      - name: Export matrix variables (if any)
+#        uses: ./test-infra/.github/actions/export-matrix-variables
+#        if: ${{ inputs.binary-matrix != '' }}
+#        with:
+#          binary-matrix: ${{ inputs.binary-matrix }}
+#          target-os: "linux"
+#
+#      - name: Run script in container
+#        if: ${{ inputs.run-with-docker == true }}
+#        continue-on-error: ${{ inputs.continue-on-error }}
+#        working-directory: ${{ inputs.repository }}
+#        env:
+#          ALL_SECRETS: ${{ toJSON(secrets) }}
+#          DOCKER_IMAGE: ${{ steps.calculate-docker-image.outputs.docker-image }}
+#        run: |
+#          set -ex
+#          {
+#            echo "#!/usr/bin/env bash";
+#            echo "set -eou pipefail";
+#            # shellcheck disable=SC2016
+#            echo 'eval "$(conda shell.bash hook)"';
+#            echo "set -x";
+#            echo "${SCRIPT}";
+#          } > "${RUNNER_TEMP}/exec_script"
+#          chmod +x "${RUNNER_TEMP}/exec_script"
+#          python3 "${{ github.workspace }}/test-infra/.github/scripts/run_with_env_secrets.py" "${{ inputs.secrets-env }}"
+#
+#      - name: Run script outside container
+#        if: ${{ inputs.run-with-docker == false }}
+#        continue-on-error: ${{ inputs.continue-on-error }}
+#        working-directory: ${{ inputs.repository }}
+#        env:
+#          ALL_SECRETS: ${{ toJSON(secrets) }}
+#        run: |
+#          {
+#            echo "#!/usr/bin/env bash";
+#            echo "set -eou pipefail";
+#            # Source conda so it's available to the script environment
+#            echo "${SCRIPT}";
+#          } > "${RUNNER_TEMP}/exec_script"
+#          # The GITHUB_WORKFLOW env var contains the name of the workflow
+#          # defined at the top of the workflow file. Unfortunately this is not
+#          # enclosed in quotes in the env file, so simply eval-ing each line in
+#          # the file will fail. As a workaround, we eval all env vars except
+#          # for GITHUB_WORKFLOW here.
+#          while read -r line; do
+#            if [[ "${line}" != "GITHUB_WORKFLOW="* ]]; then
+#              eval "export ${line}"
+#            fi
+#          done < "${RUNNER_TEMP}/github_env_${GITHUB_RUN_ID}"
+#          bash "${RUNNER_TEMP}/exec_script"
+#
+#      - name: Surface failing tests
+#        if: always()
+#        uses: pmeier/pytest-results-action@v0.3.0
+#        with:
+#          path: ${{ env.RUNNER_TEST_RESULTS_DIR }}
+#          fail-on-empty: false
+#
+#      - name: Chown repository directory
+#        if: always()
+#        uses: ./test-infra/.github/actions/chown-directory
+#        with:
+#          directory: ${{ github.workspace }}/${{ env.repository }}
+#          ALPINE_IMAGE: ${{ inputs.runner == 'linux.arm64.2xlarge' && 'arm64v8/alpine' || '308535385114.dkr.ecr.us-east-1.amazonaws.com/tool/alpine' }}
+#
+#      - name: Chown runner temp
+#        if: always()
+#        uses: ./test-infra/.github/actions/chown-directory
+#        with:
+#          directory: ${{ env.RUNNER_TEMP }}
+#          ALPINE_IMAGE: ${{ inputs.runner == 'linux.arm64.2xlarge' && 'arm64v8/alpine' || '308535385114.dkr.ecr.us-east-1.amazonaws.com/tool/alpine' }}
+#
+#      - name: Prepare artifacts for upload
+#        working-directory: ${{ inputs.repository }}
+#        id: check-artifacts
+#        env:
+#          UPLOAD_ARTIFACT_NAME: ${{ inputs.upload-artifact }}
+#        run: |
+#          # Only do these steps if we actually want to upload an artifact
+#          if [[ -n "${UPLOAD_ARTIFACT_NAME}" ]]; then
+#            # If the default execution path is followed then we should get a wheel in the dist/ folder
+#            # attempt to just grab whatever is in there and scoop it all up
+#            if find "dist/" -name "*.whl" >/dev/null 2>/dev/null; then
+#              mv -v dist/*.whl "${RUNNER_ARTIFACT_DIR}/"
+#            fi
+#            # Set to fail upload step if there are no files for upload and expected files for upload
+#            echo 'if-no-files-found=error' >> "${GITHUB_OUTPUT}"
+#          fi
+#
+#          upload_docs=0
+#          # Check if there are files in the documentation folder to upload, note that
+#          # empty folders do not count
+#          if find "${RUNNER_DOCS_DIR}" -mindepth 1 -maxdepth 1 -type f | read -r; then
+#            # TODO: Add a check here to test if on ec2 because if we're not on ec2 then this
+#            # upload will probably not work correctly
+#            upload_docs=1
+#          fi
+#          echo "upload-docs=${upload_docs}" >> "${GITHUB_OUTPUT}"
+#
+#      - name: Upload artifacts to GitHub (if any)
+#        uses: actions/upload-artifact@v3
+#        if: ${{ inputs.upload-artifact != '' }}
+#        with:
+#          name: ${{ inputs.upload-artifact }}
+#          path: ${{ runner.temp }}/artifacts/
+#          if-no-files-found: ${{ steps.check-artifacts.outputs.if-no-files-found }}
+#
+#      - name: Upload documentation to S3 (if any)
+#        uses: seemethere/upload-artifact-s3@v5
+#        if: ${{ steps.check-artifacts.outputs.upload-docs == 1 && github.event.pull_request.number != '' }}
+#        with:
+#          retention-days: 14
+#          s3-bucket: doc-previews
+#          if-no-files-found: error
+#          path: ${{ env.RUNNER_DOCS_DIR }}
+#          # ${{ env.repository }} is $OWNER/$REPO
+#          s3-prefix: ${{ env.REPOSITORY }}/${{ github.event.pull_request.number }}
+#
+#      - name: Teardown Linux
+#        if: ${{ always() }}
+#        uses: ./test-infra/.github/actions/teardown-linux
+#
+#      - name: Clean workspace after tear down
+#        if: ${{ always() }}
+#        env:
+#          NO_SUDO: ${{ inputs.no-sudo }}
+#          REPOSITORY: ${{ inputs.repository || github.repository }}
+#        run: |
+#          set +e
+#          if [[ "${NO_SUDO}" == "false" ]]; then
+#            sudo rm -rf "${GITHUB_WORKSPACE:?}/${REPOSITORY:?}"
+#          else
+#            rm -rf "${GITHUB_WORKSPACE:?}/${REPOSITORY:?}"
+#          fi
+#          set -e
