[hud] store rockset lambdas in version control
This PR uses the Rockset CLI to store our lambdas locally. It also adds
a CI check to make sure our local stuff is in sync with Rockset.

[ghstack-poisoned]

diff --git a/.github/workflows/torchci.yml b/.github/workflows/torchci.yml
--- a/.github/workflows/torchci.yml
+++ b/.github/workflows/torchci.yml
@@ -6,6 +6,11 @@ on:
   push:
     branches:
       - main
+
+defaults:
+  run:
+    working-directory: torchci
+
 jobs:
   test:
     runs-on: ubuntu-20.04
@@ -13,8 +18,23 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v2
       - name: Install
-        run: cd torchci && yarn install --frozen-lockfile
+        run: yarn install --frozen-lockfile
       - name: Lint
-        run: cd torchci && yarn lint
+        run: yarn lint
       - name: Test
-        run: cd torchci && yarn test
+        run: yarn test
+
+  check-rockset:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+      - name: Install
+        run: yarn install --frozen-lockfile
+      - name: Authorize rockset
+        run: yarn run rockset auth add default ${{ secrets.ROCKSET_API_KEY }}
+      - name: Download query lambdas
+        run: yarn run rockset local download -y
+      - name: Check for differences
+        run: |
+          git diff-index --quiet HEAD -- || (git diff; echo '::error::Diff between query lambdas in Rockset and in your local checkout, make sure they are in sync by either deploying your new code or downloading existing lambdas! See workflow log for diff.'; return 1)
